// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

// proto的包名,一个文件就是一个package,用于其他proto文件import此文件时解析

package hellopb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hello service

func NewHelloEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hello service

type HelloService interface {
	// 接口名称
	SayHello(ctx context.Context, in *SayHelloReq, opts ...client.CallOption) (*SayHelloResp, error)
}

type helloService struct {
	c    client.Client
	name string
}

func NewHelloService(name string, c client.Client) HelloService {
	return &helloService{
		c:    c,
		name: name,
	}
}

func (c *helloService) SayHello(ctx context.Context, in *SayHelloReq, opts ...client.CallOption) (*SayHelloResp, error) {
	req := c.c.NewRequest(c.name, "Hello.SayHello", in)
	out := new(SayHelloResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloHandler interface {
	// 接口名称
	SayHello(context.Context, *SayHelloReq, *SayHelloResp) error
}

func RegisterHelloHandler(s server.Server, hdlr HelloHandler, opts ...server.HandlerOption) error {
	type hello interface {
		SayHello(ctx context.Context, in *SayHelloReq, out *SayHelloResp) error
	}
	type Hello struct {
		hello
	}
	h := &helloHandler{hdlr}
	return s.Handle(s.NewHandler(&Hello{h}, opts...))
}

type helloHandler struct {
	HelloHandler
}

func (h *helloHandler) SayHello(ctx context.Context, in *SayHelloReq, out *SayHelloResp) error {
	return h.HelloHandler.SayHello(ctx, in, out)
}
